config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :profiles
  
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'pages#index', as: :root
    end
  end

  get '/about', to: 'pages#about'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_rich_text :body
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_pic

  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}"
    else
      "User1234"
    end
  end

  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :set_user
  def index
    @title = 'Home'
  end

  def about
    @title = "About"
  end

  def set_user
    @user = current_user if user_signed_in?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user

  def index
    @posts = Post.order(id: :desc)
  end


  def new
    @post = Post.new
  end

  def show
    set_post
   
  end
  


  def create 
    @post = Post.new(user_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to :posts
    else
      flash[:alert] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    set_post
  end

  def update
    @post = set_post
      if @post.update_attributes(user_params)
        flash[:notice] = "Post was successfully updated"
        redirect_to  :posts
      else
        flash[:alert] = "Something went wrong"
        render 'edit'
      end
  end
  

  def destroy
    @object = Post.find(params[:id])
    if @object.destroy
      flash[:notice] = 'Post was successfully deleted.'
      redirect_to posts_url
    else
      flash[:alert] = 'Something went wrong'
      redirect_to 'index'
    end
  end
  
  
  
  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = current_user if user_signed_in?
  end

  def user_params
    params.require(:post).permit(:title, :body, :category_id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_current_user

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to posts_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find_or_create_by(user_id: params[:id])
    end

    def set_current_user
      @user = current_user if user_signed_in?
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :profile_pic, :gender, :dob)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def def new
    
    end


    def create

      user = User.find_by(eamil: params[:session][:eamil].downcase)

      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Logged in succesfully"
        redirect_to :posts
      else
        flash.now[:alert] = "Invalid credentials"
        render 'new'
      end
     
    end
    
    def destroy
      session[:user_id] = nil  
      flash[:notice] = "You are logged out!"
      redirect_to root_path  
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_messages.html.erb
<% if alert %>

  <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
    <h3 class="alert"><%= alert %></h3>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

<% end %>


<% if notice %>
<div class="alert alert-success alert-dismissible fade show text-center" role="alert">
  <h3 class="notice"><%= notice %></h3>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Disqus</title>
  <%= favicon_link_tag %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>  


  <%= stylesheet_link_tag "bootstrap", "mdb",  media: "all" %>
  <%= javascript_include_tag "jquery", "bootstrap",  media: "all" %>
  <%= javascript_include_tag "mdb", "popper.min",  media: "all" %>

  <style>
       
        body{
           /* background: url('../assets/index.jpg') no-repeat center center fixed;  */
           background-color:#f5f5f5;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
          font-family: Arial, Helvetica, sans-serif;
        }

        #navv a{
        color: #f2f2f2;
        text-decoration:none;
        }

        .foot {
          position:absolute;
          bottom:0;
          width:100%;
          height:60px;   /* Height of the footer */
          }
    </style>

</head>

<body>

  <%= render  "partials/navbar" %>
  <br>

<div class="container">
  <%= render "layouts/messages" %>
  <%= yield %>
</div>
  

  <br><br>
     <footer class="page-footer font-small fixed-bottom" id="foot">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright: Disqus
    </div>
    <!-- Copyright -->
  </footer>

   <script>
     $("document").ready(function () {

          setTimeout(function () {
              $(".alert").remove();
          }, 2000); // 2 secs
      });
  </script>

</body>

</html>

app/views/pages/about.html.erb
<div class="card-header btn-default">

<a href="<%= posts_path %>">
  <%= image_tag "back.png"%>
</a>
  <h2 class="text-white text-center">Who Are We?</h2>
</div>
<div class="card p-3 d-flex justify-content-center">
  <%= image_tag "about.jpg", size: "720x500", class:"card-img-top", alt: "Edit Entry" %>
  <br>  

  <h3 class="text-center">Let's Disqus!!</h3>
  <p>
  
  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quia sapiente eius maxime omnis, repellendus nam assumenda nesciunt blanditiis,
   nostrum reiciendis beatae tempora totam laboriosam iste quo? Fuga eligendi ad dolorem.
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo id necessitatibus, 
    quaerat ad blanditiis modi! Hic est, quod error corrupti voluptate aspernatur blanditiis fugiat porro, possimus illo corporis omnis praesentium?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam ea doloremque voluptate, dolor non sapiente harum ut fugiat quos rerum deserunt maiores 
    omnis sunt vel tempora totam repudiandae dolorum. Earum?
  </p>
</div>

app/views/pages/index.html.erb
<div class="container">

    <div style="margin-top: 9%; text-align: center;" >

     <h1>DISQUS</h1>
       <h3>Welcome to Disqus!</h3>
         <p>
          This is a place where you can share your thoughts <br> and experience as well as hear form others.
         </p>

         <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %>

          <%= link_to "Sign In", new_user_session_path, class: "btn btn-cyan" %>

         <br> <br> <br>
         <br> <br> <br>
         
    </div>
</div>

app/views/partials/_navbar.html.erb
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light default-color lighten-4 sticky-top" id="navv">
      <div class="container">
          <a class="navbar-brand" href="index.html">
              <img src="" class="logo" alt="">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <ul class="navbar-nav">
                     <li class="nav-item mr-3">
                      <%= link_to "Home", user_signed_in? ? :root : :authenticated_root, class: "nav-link"%>
                  </li>

                <% if !user_signed_in?%>
                  <li class="nav-item mr-3">
                      <%= link_to "Posts", :posts, class: "nav-link"%>
                  </li>
                <% end %>

                  <li class="nav-item mr-3">
                      <%= link_to "About", '/about', class: "nav-link"%>
                  </li>
              </ul>

              <ul class="navbar-nav ml-auto">

                  <% if user_signed_in? %>

                  <li class="nav-item mr-3">
                   <span class="nav-link">Welcome <%= @user.profile ? @user.profile.full_name : 'User' %> </span> 
                  </li>

                  <li class="nav-item mr-3">
                      <%= button_to "Sign Out", destroy_user_session_path,  method: :delete, class: "nav-link" %>
                  </li>

                  <% else %>

                  <li class="nav-item mr-3">
                      <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item mr-3">
                      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                  </li>

                  <% end %>

              </ul>

          </div>
      </div>
  </nav>
  <!--/.Navbar -->

app/views/posts/edit.html.erb
 <div class="row d-flex justify-content-center">
  <div class="col-lg-10 text-center">

   
  <div class="card mx-auto">
      <h3 class=" card-header btn-default">Edit Post</h3>

    <% if @post.errors.any?%>
    <h3>The follwoing prevented submission!</h3>
    <% @post.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
    <% end %>
    <!-- Default form contact -->


    <%= form_with(model: @post, class: "border border-light p-5", local: true ) do |form| %>

    <!-- Title -->
    <label for="">Title</label>
    <%= form.text_field :title, class: "form-control mb-4", value: @post.title  %>

    <div class="form-group">
    <!-- Subject -->
    <label>Category</label>
    <%= form.select(:category_id,[],{}, {class: "browser-default custom-select"}) do %>
      <% Category.all.each do |category| %>
        <%= content_tag(:option, category.name, value: category.id, :selected => category.id == @post.category_id )%>
     <% end %>
    <% end %>
    </div>

    <!-- Body -->
    <label for="">Body</label>
    <div class="form-group">
      <%= form.rich_text_area :body, style: "overflow-y: scroll; height: 200px;" %>
    </div>

    <!-- Send button -->
    <%= form.submit "Update", class: "btn btn-success", disable_with: 'Updating...' %>
    <%= link_to "Cancel", posts_path, class: "btn btn-warning" %>

    <% end %>

  </div>
  </div>
  </div>

app/views/posts/index.html.erb
<style>
  .btn-grp {
    display: inline-block;
  }

  .post {
    color: black;
  }

  .post:hover {
    color: blue;
    text-decoration: underline;
  }

  #content{
    white-space: nowrap; 
    width: 100%; 
    overflow: hidden;
    text-overflow: clip; 
  }
</style>

<div class="container">
  <div class="row">
    <div class="col-sm">

      <!-- Card -->
      <div class="card">

        <!-- Card image -->
        <% if user_signed_in? %>
        <div class="view overlay">

          <%
=begin%>
 <% if @user.profile.profile_pic.attached?%>
          <%= image_tag @user.profile.profile_pic, size: "200x200", class:"card-img-top" %>
          <% else %> 
<%
=end%>
          <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
            alt="Card image cap">
          <%
=begin%>
 <% end%> 
<%
=end%>
          <a href="#!">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
        <% end %>
        <!-- Card content -->
        <div class="card-body text-center">

          <!-- Title -->
          <h4 class="card-title">Profile</h4>
          <!-- Text -->
          <div class="card-text">

            <% if user_signed_in? %>
            <p><%= @user.profile ? @user.profile.full_name : 'User' %> </p>
            <% else %>
            <p>You aren't signed in!!</p>
            <% end %>

          </div>
          <!-- Button -->
          <% if user_signed_in?%>
          <%= link_to "Edit Profile", edit_profile_path(id: @user.id), class: "btn btn-primary btn-sm"%>
          <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-sm" %>
          <% end %>

        </div>

      </div>
      <!-- Card -->


      <%# new section %>
      <br>
      <div class="card">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Cras justo odio</li>
          <li class="list-group-item">Dapibus ac facilisis in</li>
          <li class="list-group-item">Vestibulum at eros</li>
        </ul>
      </div>
    </div>

    <div class="col-sm-6">
      <a href="posts/new" class="post">
        <div class="card w-100 h-25 p-3">
          <h3 class="text-center"> <%= image_tag "new.png"%> Make a post</h3>
        </div>
      </a><br>
      <% if @posts %>
      <% @posts.each do |post| %>

      <div class="card">
        <div class="card-body">
          <div class="card-title text-left"><span>
          <h6><small><%= post.user.profile ? post.user.profile.full_name : 'User' %> &#8226; <%= post.created_at.strftime("on %d/%m/%Y") %>
                </small></h6>
              <h5 class="d-inline"> <%= post.title%></h5>
          </div>
          <article class="card-text">
            <div id="content"><%= post.body %> </div>
          </article>
          <div class="row d-flex justify-content-center">
            <%= link_to "View More", post, class: "btn btn-sm btn-outline-primary btn-grp" %>
            <% if user_signed_in? && @user.id == post.user_id%>
            <%= link_to "Edit", edit_post_path(post), class: "btn btn-sm btn-outline-secondary btn-grp" %>
            <%= button_to "Delete", post_path(post), data: { turbolinks: false, confirm: "Are you sure?" }, method: :delete,  class: "btn btn-sm btn-outline-danger btn-grp" %>
            <% end %>
          </div>
        </div>
      </div> <br>
      <% end %>
      <% else %>
      <div class="card text-center">
        <div class="card-body">
          <div class="card-text">
            <h3>No Articles Available <i class="far fa-sad-tear"></i></h3>
            <h5>Be the first to make a post</h5>
          </div>
        </div>
      </div>
      <% end %>
    </div>

  <div class="col-sm mt-5">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Information</li>
        <li class="list-group-item">Entertainment</li>
        <li class="list-group-item">Personal</li>
      </ul>
    </div>
  </div>

  <%# end of row %>
</div>
</div> <br>

app/views/posts/new.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-lg-10 text-center">
  <div class="card mx-auto">

    <h3 class="card-header bg-primary text-white text-center">New Post</h3>
    <% if @post.errors.any?%>
    <h3>The follwoing prevented submission!</h3>
    <% @post.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
    <% end %>
    <!-- Default form contact -->


    <%= form_with(model: @post, class: "border border-light p-5", local: true ) do |form| %>


    <!-- Title -->
    <%= form.text_field :title, class: "form-control mb-4", placeholder: "Title"   %>

    <!-- Category -->
    <label>Category</label>
    <%= form.select(:category_id, [],{}, {:class => "browser-default custom-select"}) do %>
    <% Category.all.each do |category| %>
    <%= content_tag(:option, category.name, value:category.id ) %>
    <% end %>
    <% end %>

    <br><br>
    <!-- Body -->
    <div class="form-group">
      <%= form.rich_text_area :body, style: "overflow-y: scroll; height: 200px;" %>
    </div>

    <!-- Send button -->
    <%= form.submit "Create", class: "btn btn-success btn-block", disable_with: 'Createing...' %>
    <%= link_to 'Back', posts_path, class: "btn btn-warning" %>

    <% end %>
    <!-- Default form contact -->

  </div>
  </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="card p-3 mx-auto">
   <a href="<%= posts_path %>">
  <%= image_tag "back.png"%>
</a>
    <h2 class="card-title text-center"><%= @post.title %></h2>
    <hr>

    <p> <%= @post.body %> </p>

    <div class="row d-flex justify-content-center">
      <% if user_signed_in? && @user.id == @post.user_id%>
      <%= link_to "Edit", edit_post_path(@post), class: "btn btn-sm btn-outline-secondary btn-grp" %>
      <%= button_to "Delete", post_path(@post), data: { turbolinks: false, confirm: "Are you sure?" }, method: :delete,  class: "btn btn-sm btn-outline-danger btn-grp" %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="custom-file">
     <%= form.file_field :profile_pic, class: "custom-file-input", id: "inputGroupFile01" %>
     <label class="custom-file-label" for="inputGroupFile01">Profile Picture</label>
    </div> <br><br>

    <%= form.text_field :first_name, class: "form-control mb-4", placeholder: "First Name" %>

    <%= form.text_field :last_name, class: "form-control mb-4", placeholder: "Last Name" %>

    <%= form.date_field :dob, class: "form-control mb-4", placeholder: "DOB" %>

    <%= form.text_field :gender, class: "form-control mb-4", placeholder: "Gender" %>

    <%= form.submit class: "btn btn-info btn-block my-4" %>
    <%= link_to 'Back', posts_path, class: "btn btn-warning" %>
<% end %>

app/views/profiles/edit.html.erb
<h1 class="text-center">Editing Profile</h1>
<hr>

<div class="row d-flex justify-content-center">
  <div class="col-lg-6 text-center">
    <div class="card p-3">
       <%= render 'form', profile: @profile %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<%= link_to 'Edit', edit_profile_path(id: @profile.user_id) %> |
<%= link_to 'Back', profiles_path %>